language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t ryanskinner93/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ryanskinner93/react-test npm test -- --coverage

after_success:
  - docker build -t ryanskinner93/multi-client ./client
  - docker build -t ryanskinner93/multi-nginx ./nginx
  - docker build -t ryanskinner93/multi-server ./server
  - docker build -t ryanskinner93/multi-worker ./worker
  # Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ryanskinner93/multi-client
  - docker push ryanskinner93/multi-nginx
  - docker push ryanskinner93/multi-server
  - docker push ryanskinner93/multi-worker
